// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs.go

package x11

import "unsafe"

type XAnyEvent struct {
	Type	int32
	Serial	uint64
	Event	int32
	Display	unsafe.Pointer
	Window	uint64
}
type XKeyEvent struct {
	Type		int32
	Serial		uint64
	Send_event	int32
	Display		unsafe.Pointer
	Window		uint64
	Root		uint64
	Subwindow	uint64
	Time		uint64
	X		int32
	Y		int32
	X_root		int32
	Y_root		int32
	State		uint32
	Keycode		uint32
	Same_screen	int32
	Pad_cgo_0	[4]byte
}
type XButtonEvent struct {
	Type		int32
	Serial		uint64
	Send_event	int32
	Display		unsafe.Pointer
	Window		uint64
	Root		uint64
	Subwindow	uint64
	Time		uint64
	X		int32
	Y		int32
	X_root		int32
	Y_root		int32
	State		uint32
	Button		uint32
	Same_screen	int32
	Pad_cgo_0	[4]byte
}
type XMotionEvent struct {
	Type		int32
	Serial		uint64
	Send_event	int32
	Display		unsafe.Pointer
	Window		uint64
	Root		uint64
	Subwindow	uint64
	Time		uint64
	X		int32
	Y		int32
	X_root		int32
	Y_root		int32
	State		uint32
	Is_hint		int8
	Same_screen	int32
	Pad_cgo_0	[4]byte
}

type XtResource struct {
	Resource_name	*int8
	Resource_class	*int8
	Resource_type	*int8
	Resource_size	uint32
	Resource_offset	uint32
	Default_type	*int8
	Default_addr	*byte
}
type XtResourceList *XtResource

type XGCValues struct {
	Function		int32
	Plane_mask		uint64
	Foreground		uint64
	Background		uint64
	Line_width		int32
	Line_style		int32
	Cap_style		int32
	Join_style		int32
	Fill_style		int32
	Fill_rule		int32
	Arc_mode		int32
	Tile			uint64
	Stipple			uint64
	Ts_x_origin		int32
	Ts_y_origin		int32
	Font			uint64
	Subwindow_mode		int32
	Graphics_exposures	int32
	Clip_x_origin		int32
	Clip_y_origin		int32
	Clip_mask		uint64
	Dash_offset		int32
	Dashes			int8
	Pad_cgo_0		[3]byte
}

type XPoint struct {
	X	int16
	Y	int16
}

type XArc struct {
	X	int16
	Y	int16
	Width	uint16
	Height	uint16
	Angle1	int16
	Angle2	int16
}