// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs defs.go

package x11

import "unsafe"

type XAnyEvent struct {
	Type	int32
	Serial	uint64
	Event	int32
	Display	unsafe.Pointer
	Window	uint64
}
type XKeyEvent struct {
	Type		int32
	Serial		uint64
	Send_event	int32
	Display		unsafe.Pointer
	Window		uint64
	Root		uint64
	Subwindow	uint64
	Time		uint64
	X		int32
	Y		int32
	X_root		int32
	Y_root		int32
	State		uint32
	Keycode		uint32
	Same_screen	int32
	Pad_cgo_0	[4]byte
}
type XButtonEvent struct {
	Type		int32
	Serial		uint64
	Send_event	int32
	Display		unsafe.Pointer
	Window		uint64
	Root		uint64
	Subwindow	uint64
	Time		uint64
	X		int32
	Y		int32
	X_root		int32
	Y_root		int32
	State		uint32
	Button		uint32
	Same_screen	int32
	Pad_cgo_0	[4]byte
}
type XMotionEvent struct {
	Type		int32
	Serial		uint64
	Send_event	int32
	Display		unsafe.Pointer
	Window		uint64
	Root		uint64
	Subwindow	uint64
	Time		uint64
	X		int32
	Y		int32
	X_root		int32
	Y_root		int32
	State		uint32
	Is_hint		int8
	Same_screen	int32
	Pad_cgo_0	[4]byte
}
