package x11

/*
#include <stdint.h>
#include <stdlib.h>

// Xt includes
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include "cheader.h"
#include "wrapperInfo.h"


*/
import "C"
import "unsafe"

func ApplicationShellWidgetClass() WidgetClass {
	return WidgetClass(unsafe.Pointer(C.applicationShellWidgetClass))
}

// String defines
var XtNaccelerators = C.GoString(C.XtNaccelerators)
var XtNallowHoriz = C.GoString(C.XtNallowHoriz)
var XtNallowVert = C.GoString(C.XtNallowVert)
var XtNancestorSensitive = C.GoString(C.XtNancestorSensitive)
var XtNbackground = C.GoString(C.XtNbackground)
var XtNbackgroundPixmap = C.GoString(C.XtNbackgroundPixmap)
var XtNbitmap = C.GoString(C.XtNbitmap)
var XtNborderColor = C.GoString(C.XtNborderColor)
var XtNborder = C.GoString(C.XtNborder)
var XtNborderPixmap = C.GoString(C.XtNborderPixmap)
var XtNborderWidth = C.GoString(C.XtNborderWidth)
var XtNcallback = C.GoString(C.XtNcallback)
var XtNchildren = C.GoString(C.XtNchildren)
var XtNcolormap = C.GoString(C.XtNcolormap)
var XtNdepth = C.GoString(C.XtNdepth)
var XtNdestroyCallback = C.GoString(C.XtNdestroyCallback)
var XtNeditType = C.GoString(C.XtNeditType)
var XtNfile = C.GoString(C.XtNfile)
var XtNfont = C.GoString(C.XtNfont)
var XtNforceBars = C.GoString(C.XtNforceBars)
var XtNforeground = C.GoString(C.XtNforeground)
var XtNfunction = C.GoString(C.XtNfunction)
var XtNheight = C.GoString(C.XtNheight)
var XtNhighlight = C.GoString(C.XtNhighlight)
var XtNhSpace = C.GoString(C.XtNhSpace)
var XtNindex = C.GoString(C.XtNindex)
var XtNinitialResourcesPersistent = C.GoString(C.XtNinitialResourcesPersistent)
var XtNinnerHeight = C.GoString(C.XtNinnerHeight)
var XtNinnerWidth = C.GoString(C.XtNinnerWidth)
var XtNinnerWindow = C.GoString(C.XtNinnerWindow)
var XtNinsertPosition = C.GoString(C.XtNinsertPosition)
var XtNinternalHeight = C.GoString(C.XtNinternalHeight)
var XtNinternalWidth = C.GoString(C.XtNinternalWidth)
var XtNjumpProc = C.GoString(C.XtNjumpProc)
var XtNjustify = C.GoString(C.XtNjustify)
var XtNknobHeight = C.GoString(C.XtNknobHeight)
var XtNknobIndent = C.GoString(C.XtNknobIndent)
var XtNknobPixel = C.GoString(C.XtNknobPixel)
var XtNknobWidth = C.GoString(C.XtNknobWidth)
var XtNlabel = C.GoString(C.XtNlabel)
var XtNlength = C.GoString(C.XtNlength)
var XtNlowerRight = C.GoString(C.XtNlowerRight)
var XtNmappedWhenManaged = C.GoString(C.XtNmappedWhenManaged)
var XtNmenuEntry = C.GoString(C.XtNmenuEntry)
var XtNname = C.GoString(C.XtNname)
var XtNnotify = C.GoString(C.XtNnotify)
var XtNnumChildren = C.GoString(C.XtNnumChildren)
var XtNorientation = C.GoString(C.XtNorientation)
var XtNparameter = C.GoString(C.XtNparameter)
var XtNpixmap = C.GoString(C.XtNpixmap)
var XtNpopupCallback = C.GoString(C.XtNpopupCallback)
var XtNpopdownCallback = C.GoString(C.XtNpopdownCallback)
var XtNresize = C.GoString(C.XtNresize)
var XtNreverseVideo = C.GoString(C.XtNreverseVideo)
var XtNscreen = C.GoString(C.XtNscreen)
var XtNscrollProc = C.GoString(C.XtNscrollProc)
var XtNscrollDCursor = C.GoString(C.XtNscrollDCursor)
var XtNscrollHCursor = C.GoString(C.XtNscrollHCursor)
var XtNscrollLCursor = C.GoString(C.XtNscrollLCursor)
var XtNscrollRCursor = C.GoString(C.XtNscrollRCursor)
var XtNscrollUCursor = C.GoString(C.XtNscrollUCursor)
var XtNscrollVCursor = C.GoString(C.XtNscrollVCursor)
var XtNselection = C.GoString(C.XtNselection)
var XtNselectionArray = C.GoString(C.XtNselectionArray)
var XtNsensitive = C.GoString(C.XtNsensitive)
var XtNshown = C.GoString(C.XtNshown)
var XtNspace = C.GoString(C.XtNspace)
var XtNstring = C.GoString(C.XtNstring)
var XtNtextOptions = C.GoString(C.XtNtextOptions)
var XtNtextSink = C.GoString(C.XtNtextSink)
var XtNtextSource = C.GoString(C.XtNtextSource)
var XtNthickness = C.GoString(C.XtNthickness)
var XtNthumb = C.GoString(C.XtNthumb)
var XtNthumbProc = C.GoString(C.XtNthumbProc)
var XtNtop = C.GoString(C.XtNtop)
var XtNtranslations = C.GoString(C.XtNtranslations)
var XtNunrealizeCallback = C.GoString(C.XtNunrealizeCallback)
var XtNupdate = C.GoString(C.XtNupdate)
var XtNuseBottom = C.GoString(C.XtNuseBottom)
var XtNuseRight = C.GoString(C.XtNuseRight)
var XtNvalue = C.GoString(C.XtNvalue)
var XtNvSpace = C.GoString(C.XtNvSpace)
var XtNwidth = C.GoString(C.XtNwidth)
var XtNwindow = C.GoString(C.XtNwindow)
var XtNx = C.GoString(C.XtNx)
var XtNy = C.GoString(C.XtNy)
var XtNfontSet = C.GoString(C.XtNfontSet)
var XtNcreateHook = C.GoString(C.XtNcreateHook)
var XtNchangeHook = C.GoString(C.XtNchangeHook)
var XtNconfigureHook = C.GoString(C.XtNconfigureHook)
var XtNgeometryHook = C.GoString(C.XtNgeometryHook)
var XtNdestroyHook = C.GoString(C.XtNdestroyHook)
var XtNshells = C.GoString(C.XtNshells)
var XtNnumShells = C.GoString(C.XtNnumShells)
