// Code generated by cmd/cgo; DO NOT EDIT.

//line /home/dennis/GolandProjects/awesomeProject1/main.go:1:1
package main

// #cgo LDFLAGS: -lXt -lX11
// #include <X11/Intrinsic.h>
// #include <Xm/Xm.h>          /* Required by all Motif applications */
// #include <Xm/Label.h>       /* Required by XmLabel widget */
// #include <hello.h>
import _ "unsafe"
import "fmt"

/*

/
extern Widget XtAppInitialize(
XtAppContext*       ,
_Xconst _XtString  ,
XrmOptionDescList  ,
Cardinal            ,
int*                ,
_XtString*          ,
String*             ,
ArgList             ,
Cardinal
)

*/

func main() {
	( /*line :29:2*/_Cfunc_hello1 /*line :29:9*/)()

	appClass := "AppClass"
	var ctx = new(AppContext)
	var options = new(OptionDescList)
	var argList = new(ArgList)

	c_appClass := ( /*line :36:16*/_Cfunc_CString /*line :36:24*/)(appClass)
	var cargc  /*line :37:12*/_Ctype_int /*line :37:17*/ = 0
	var cargv ** /*line :38:14*/_Ctype_char /*line :38:20*/
	var cnumOptions  /*line :39:18*/_Ctype_uint /*line :39:24*/ = 0
	c_fallbackResources := ( /*line :40:25*/_Cfunc_XtNewString /*line :40:37*/)(( /*line :40:39*/_Cfunc_CString /*line :40:47*/)(""))
	cnumArgs :=  /*line :41:14*/_Ctype_uint /*line :41:20*/(0)
	shell := func() _Ctype_Widget{ _cgoBase0 := /*line :42:29*/&ctx.appContext; _cgo0 := _cgoBase0; var _cgo1 *_Ctype_char = /*line :42:46*/c_appClass; _cgo2 := /*line :42:58*/options.optionDescList; var _cgo3 _Ctype_Cardinal = /*line :42:82*/cnumOptions; var _cgo4 *_Ctype_int = /*line :43:3*/&cargc; _cgo5 := /*line :43:11*/cargv; _cgoBase6 := /*line :43:18*/&c_fallbackResources; _cgo6 := _cgoBase6; _cgo7 := /*line :43:40*/argList.argList; var _cgo8 _Ctype_Cardinal = /*line :43:57*/cnumArgs; _cgoCheckPointer(_cgoBase0, 0 == 0); _cgoCheckPointer(_cgo2, nil); _cgoCheckPointer(_cgo5, nil); _cgoCheckPointer(_cgoBase6, 0 == 0); _cgoCheckPointer(_cgo7, nil); return /*line :43:66*/_Cfunc_XtAppInitialize(_cgo0, _cgo1, _cgo2, _cgo3, _cgo4, _cgo5, _cgo6, _cgo7, _cgo8); }()

	/* Convert the first argument to the form expected by Motif */
	xmstr := ( /*line :46:11*/_Cfunc_XmStringCreateLtoR /*line :46:30*/)(( /*line :46:32*/_Cfunc_CString /*line :46:40*/)("hehe"), ( /*line :46:51*/_Cmacro_XmFONTLIST_DEFAULT_TAG() /*line :46:74*/))

	/* Create a Motif XmLabel widget to display the string */
	/* C.XmNlabelString, xmstr, */
	var wargc  /*line :50:12*/_Ctype_uint /*line :50:18*/ = 1
	var wargs  /*line :51:12*/_Ctype_Arg /*line :51:17*/
	//C.XtSetArg(wargs[0], C.XmNlabelString, "hehe test")
	wargs.name = ( /*line :53:15*/_Cmacro_XmNlabelString() /*line :53:30*/)
	wargs.value =  /*line :54:16*/_Ctype_XtArgVal /*line :54:26*/(xmstr)

	msg := func() _Ctype_Widget{ var _cgo0 *_Ctype_char = _Cfunc_CString /*line :56:42*/("message"); _cgo1 := /*line :57:3*/*_Cvar_xmLabelWidgetClass /*line :57:23*/; _cgo2 := /*line :57:25*/shell; _cgoBase3 := /*line :58:3*/&wargs; _cgo3 := _cgoBase3; var _cgo4 _Ctype_Cardinal = /*line :59:3*/wargc; _cgoCheckPointer(_cgo1, nil); _cgoCheckPointer(_cgo2, nil); _cgoCheckPointer(_cgoBase3, 0 == 0); return /*line :59:9*/_Cfunc_XtCreateManagedWidget(_cgo0, _cgo1, _cgo2, _cgo3, _cgo4); }()
	fmt.Printf("%x\n", msg)

	func() { _cgo0 := /*line :62:17*/xmstr; _cgoCheckPointer(_cgo0, nil); /*line :62:23*/_Cfunc_XmStringFree(_cgo0); }() /* Free the compound string */

	/*
	 * Realize the shell and enter an event loop.
	 */

	func() { _cgo0 := /*line :68:20*/shell; _cgoCheckPointer(_cgo0, nil); /*line :68:26*/_Cfunc_XtRealizeWidget(_cgo0); }()
	func() { _cgo0 := /*line :69:18*/ctx.appContext; _cgoCheckPointer(_cgo0, nil); /*line :69:33*/_Cfunc_XtAppMainLoop(_cgo0); }()

	( /*line :71:2*/_Cfunc_hello1 /*line :71:9*/)()
}
